version: '3'
services:
  web:
    stdin_open: true
    tty: true
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: web
    volumes:
      - ./web:/opt/zher_web
      - /opt/zher_web/node_modules
    environment:
      VUE_APP_EBATYS_URL: http://localhost:22600
      VUE_APP_MAP_TOKEN: pk.eyJ1IjoiYXJ0aHVyLWtlbnRiYXlldiIsImEiOiJjazdha2V3aHYwemphM2VvZ3NqbTRqdGM0In0.pkbvKU2j4bOhdqX3RZrZKA

  api:
    stdin_open: true
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 26230:26230
    container_name: api
    volumes:
      - ./api:/opt/zher_api
      - /opt/zher_api/node_modules
    environment:
      PORT: 26230
      ACCESS_TOKEN_SECRET: fdaa498017e1cdd12aa9ae24343105097ea23596dc9262e7c853ec8c0d78a6cb4cbd6cf2cbec1418bd04e3601976a5d55f4e93201bf8dbdce46f8a9992328920
      REFRESH_TOKEN_SECRET: 3473839b3fcb3ada3874191e4d121d51d31a71e85185083fdc2118edb78b643dcc2c83d6942d2ee63c37f7841246b85a9bf5b915715b2f7c84d3fe2337ea7798
      EMAIL_TOKEN_SECRET: d8bdc680dfa88d374b2a5fe708b938c4a6f2244cffb6561c51e0df446acd73da65b2473d325fe044c8b73347f912c04c202c5b5073735e4574eefcc218893fbc
      DB_CONNECT: postgresql://postgres:postgres@192.168.53.145:5432/zher.e-batys.kz
      NODEMAILER_EMAIL: zher.ebatys.kz@gmail.com
      NODEMAILER_PASSWORD: Postgres10

  ncanode:
    stdin_open: true
    tty: true
    image: kagiskz/ncanode
    ports:
      - 14579:14579
    container_name: ncanode
